on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::497554381691:role/roke_githubactions_s3sync
          aws-region: ap-northeast-1
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync . s3://githubactionssamplekawabe/dir/ --exclude '.*git*'
